name: "Setup Nix Environment"
description: "Install Nix and set up the environment for nix-shell usage"
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v27

    - name: Setup cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Verify Nix Installation
      run: nix-shell --version
